data:
  datapath: 'data/NS_fine_Re500_s2048_T100.npy'
  Re: 500
  total_num: 500
  offset: 500
  n_sample: 1
  time_interval: 1
  nx: 256
  nt: 128
  sub: 2
  sub_t: 2
  shuffle: False

model:
  layers: [32, 32, 32, 32, 32]
  modes1: [20, 20, 20, 20]
  modes2: [20, 20, 20, 20]
  modes3: [20, 20, 20, 20]
  fc_dim: 256

train:
  batchsize: 1
  epochs: 7500
  milestones: [1000, 1500, 2500, 3500, 4500]
  base_lr: 0.0025
  scheduler_gamma: 0.5
#  ckpt: 'checkpoints/Re500-FDM/PINO_FDM_Re500_T500.pt'
  ic_loss: 1.0
  f_loss: 1.0
  xy_loss: 0
  save_dir: 'Re500-T100'
  save_name: 'PINO-fintune-T100-t1.pt'
  log: True




