data:
  paths: ['../data/NS-Re500Part0.npy', '../data/NS-Re500Part1.npy']
  Re: 500
  total_num: 200
  offset: 0
  n_sample: 700
  time_duration: 0.5
  data_res: [64, 64, 33]
  pde_res: [128, 128, 65]
  shuffle: True

model:
  layers: [64, 64, 64, 64, 64]
  modes1: [8, 8, 8, 8]
  modes2: [8, 8, 8, 8]
  modes3: [8, 8, 8, 8]
  fc_dim: 128
  act: gelu
  num_pad: 5

train:
  batchsize: 1
  epochs: 501
  milestones: [300]
  base_lr: 0.001
  scheduler_gamma: 0.5
  ic_loss: 5.0
  f_loss: 1.0
  xy_loss: 1.0
  save_step: 100

log:
  logdir: Re500-05s-PINO
  entity: hzzheng-pino
  project: 'PINO-pretrain-ICLR'
  group: 'Re500-05s-4C0'


